export const primsa_error_messages: Record<string, string> = {
  P2000: 'The value you entered is too long for the field.',
  P2001: 'The requested record does not exist.',
  P2002: 'A unique constraint failed. Please ensure the value is unique.',
  P2003: 'A foreign key constraint failed. Please check related records.',
  P2004: 'A constraint failed during the operation.',
  P2005: 'Invalid value provided for a field.',
  P2006: 'Field value does not match the expected format.',
  P2007: 'The data in the database is invalid for the field type.',
  P2008: 'A query parsing error occurred.',
  P2009: 'A validation error occurred in the query.',
  P2010: 'Raw query execution failed. Please try again.',
  P2011: 'Null constraint violation. A required field is missing.',
  P2012: 'Missing required arguments for the query.',
  P2013: 'Invalid arguments provided for the query.',
  P2014: 'A relation violation occurred. Ensure the operation is valid.',
  P2015: 'The record for the relation field could not be found.',
  P2016: 'A query interpretation error occurred.',
  P2017: 'The query returned an unexpected result.',
  P2018: 'Required connected records were not found.',
  P2019: 'Input data is invalid for the field type.',
  P2020: 'The database operation timed out. Please try again.',
  P2021: 'The database connection was lost.',
  P2022: 'A query engine initialization error occurred.',
  P2023: 'Invalid query parameters. Check your input.',
};
